server:
  port: 8085

spring:
  application:
    name: ms-envios
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.gkcyyzzaizzuglmyetpe
    password: GkCMQaTgcoo4ETva
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect